name: Bug Report
description: Report something broken
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What’s wrong?
      description: A short description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps to see the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Error shows up
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual
      description: What you expected to happen vs. what actually happened
