name: Feature
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: [enhancement]
body:
  - type: textarea
    id: build
    attributes:
      label: What to build
      description: Short description of the feature
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Any extra details
