name: Spike
description: Short research / investigation
title: "[SPIKE] "
labels: [research]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What are we trying to learn?
    validations:
      required: true

  - type: textarea
    id: deliverable
    attributes:
      label: Deliverable
      description: What should we produce at the end?
